---
# tasks file for ./z_agent
  - name: copy script
    copy:
      src: ./zabbix.sh
      dest: /tmp/zabbix.sh
  - name: start script
    command:
      bash /tmp/zabbix.sh
  - name: edit zbx server config
    command:
      echo DBPassword=pswd123 >> /etc/zabbix/zabbix_server.conf
  - name: zabbix apply config changes
    command:
      /etc/init.d/zabbix-server restart
  - name: zabbix restart apache
    command:
      /etc/init.d/apache2 restart
  - name: install zbx zabbix-agent
    command:
      apt install zabbix-agent